kanagawa = ["kawasaki",
"kawasaki-kawasaki-ku",
"kawasaki-saiwai-ku",
"kawasaki-nakahara-ku",
"kawasaki-takatsu-ku",
"kawasaki-shi-tama-ku",
"kawasaki-shi-miyamae-ku",
"kawasaki-asao-ku",
# "sagamihara",
# "sagamihara-shi-midori-ku",
# "sagamihara-chuo-ku",
# "sagamihara-minami-ku",
"yokohama",
"yokohama-shi-tsurumi-ku",
"yokohama-shi-kanagawa-ku",
"yokohama-shi-nishi-ku",
"yokohama-shi-naka-ku",
"yokohama-shi-minami-ku",
"yokohama-shi-hodogaya-ku",
"yokohama-shi-isogo-ku",
"yokohama-shi-kanazawa-ku",
"yokohama-shi-kohoku-ku",
"yokohama-shi-totsuka-ku",
"yokohama-shi-konan-ku",
"yokohama-shi-asahi-ku",
"yokohama-shi-midori-ku",
"yokohama-shi-seya-ku",
"yokohama-shi-sakae-ku",
"yokohama-shi-izumi-ku",
"yokohama-shi-aoba-ku",
"yokohama-shi-tsuzuki-ku"
# "aiko-gun-aikawa-machi",
# "aiko-gun-kiyokawa-mura",
# "ashigarakami-gun-kaisei-machi",
# "ashigarakami-matsuda-machi",
# "ashigarakami-nakai-machi",
# "ashigarakami-oi-machi",
# "ashigarakami-yamakita-machi",
# "ashigarashimo-hakone-machi",
# "ashigarashimo-gun-manazuru-machi",
# "ashigarashimo-gun-yugawara-machi",
# "atsugi",
# "ayase-shi",
# "chigasaki-shi",
# "ebina",
# "fujisawa-shi",
# "hadano",
# "hiratsuka-shi",
# "isehara-shi",
# "kamakura-shi",
# "koza-samukawa-machi",
# "minamiashigara",
# "miura-gun-hayama-machi",
# "miura",
# "naka-gun-ninomiya-machi",
# "naka-gun-oiso-machi",
# "odawara",
# "yamato",
# "yokosuka-shi",
# "zama-shi",
# "zushi-shi"
]